# Generated by Django 3.1.2 on 2020-10-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projapp', '0002_profile_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='avatars/'),
        ),
    ]
